name: CI
on: [push]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: gradle
          
      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            **/loom-cache
            **/prebundled-jars
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Change permissions
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build --no-daemon
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: QuickStatsReborn
          path: /home/runner/work/QuickStatsReborn/QuickStatsReborn/versions/1.8.9-forge/build/libs

      - name: Calculate hash of the final JAR
        id: calculate-hash
        run: |
          HASH=$(find /home/runner/work/QuickStatsReborn/QuickStatsReborn/versions/1.8.9-forge/build/libs/ -type f -name "*.jar" ! -name "*-dev.jar" -exec sha256sum {} \; | awk '{ print $1 }')
          echo "hash=$HASH" >> $GITHUB_OUTPUT

      - name: Fetch current hash list
        run: |
          mkdir -p hashes
          curl -o hashes/list https://raw.githubusercontent.com/SpoonySimone/QuickStatsReborn/refs/heads/main/hashes/list
          
      - name: Append new hash to the list
        run: |
          echo "${{ steps.calculate-hash.outputs.hash }}" > hashes/list

      - name: Commit and push updated hash list
        run: |
          git config --global user.name "Auto Hash Updater"
          git config --global user.email "actions@github.com"
          
          if ! git diff --exit-code hashes/list; then
            git add hashes/list
            git commit -m "Update hash list"
            git push
          else
            echo "No changes to commit."
          fi
