name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle

      - name: Change wrapper permissions
        run: chmod +x ./gradlew
        
      - name: Init gradle wrapper
        run: ./gradlew wrapper --gradle-version=6.8.3

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Build with Gradle wrapper
        run: ./gradlew build
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: QuickStatsReborn
          path: /home/runner/work/QuickStatsReborn/QuickStatsReborn/build/libs
